name: Crawl and index to Algolia

on:
  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

jobs:

  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get DocSearch config
        id: algolia_config
        run: echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"

      - name: Index to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
